name: Broken CI Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install thispackagedoesnotexist123

    - name: Run tests
      run: pytest
